project:
  type: website

website:
  title: "ACCT 520"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Fallacies"
        #file: tutorials.qmd
      - text: "Labs"
        #file: howto.qmd
      - text: "Course Projects"
        #file: fundamentals.qmd
      - text: "Final Project"
        #file: reference.qmd

  sidebar:
    - title: "Fallacies"
      style: "docked"
      background: dark
      #contents:
        #- tutorials.qmd
        #- tutorial-1.qmd
        #- tutorial-2.qmd

    - title: "How-To"
      #contents:
        #- howto.qmd
        # navigation items

    - title: "Fundamentals"
      #contents:
        #- fundamentals.qmd
        # navigation items

    - title: "Reference"
      #contents:
        #- reference.qmd
        # navigation items

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

