project:
  type: website

website:
  title: "ACCT 520"
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data Analytics"
        file: CRISP-DM.qmd
      - text: "Labs"
        #file: howto.qmd
      - text: "Course Projects"
        #file: fundamentals.qmd
      - text: "Final Project"
        #file: reference.qmd

  sidebar:
    - title: "Data Analytics"
      style: "docked"
      background: dark
      contents:
        - CRISP-DM.qmd
        - Fallacy-Introduction.qmd
        #- tutorial-2.qmd

    - title: "How-To"
      #contents:
        #- howto.qmd
        # navigation items

    - title: "Fundamentals"
      #contents:
        #- fundamentals.qmd
        # navigation items

    - title: "Reference"
      #contents:
        #- reference.qmd
        # navigation items

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

